---
all:
  hosts:
    etcd-0:
      ansible_host: 134.209.23.202
    etcd-1: 
      ansible_host: 134.209.23.201
    controlplane-0: 
      ansible_host: 134.209.23.203
    controlplane-1: 
      ansible_host: 134.209.20.61
    worker-0: 
      ansible_host: 134.209.23.209
    worker-1: 
      ansible_host: 134.209.23.208
    loadbalancer:
      ansible_host: 134.209.23.210

  children:
    rancher-2-kubernetes-nodes:
      children:
        etcd:
          hosts:
            etcd-0:
            etcd-1:
        controlplane:
          hosts:
            controlplane-0:
            controlplane-1:
        worker:
          hosts:
            worker-0:
            worker-1:
    rancher-2-load-balancers:
      hosts:
        loadbalancer:
